#! /bin/sh
### BEGIN INIT INFO
# Provides:          raspadmin
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Raspberry pi WebAdmin
# Description:       This script start the raspadmin, a web interface for managing your device
#
### END INIT INFO


PIDFILE=/var/run/raspadmin.pid
APPDIR=$INSTALLDIR
LOGFILE=/var/log/raspadmin/access.log
LOGERROR=/var/log/raspadmin/error.log

SSHCOMMAND="/usr/bin/python raspwebadmin.py"
case "$1" in
	start)
		$0 status > /dev/null
		if [ $? -eq 1 ] ; then
			printf "%s\n" "Already running"
			exit 3
		fi
		
		currentdir=$(pwd)
		cd $APPDIR
		PID=`$SSHCOMMAND >>$LOGFILE 2>&1 & echo $!`
	        if [ -z $PID ]; then
			printf "%s\n" "Fail"
		else
            		echo $PID > $PIDFILE
			printf "%s\n" "Ok"
       		 fi
		 cd $currentdir
	;;
	status)
		printf "%-50s" "Checking ..."
		if [ -f $PIDFILE ]; then
			PID=`cat $PIDFILE`
			if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
				printf "%s\n" "Process dead but pidfile exists"
				exit 0
			else
				echo "Running"
				exit 1
			fi
		else
			printf "%s\n" "Service not running"
		fi
	;;

	stop)
        	printf "%-50s" "Stopping $NAME"
            	PID=`cat $PIDFILE`
            	cd $DAEMON_PATH
        	if [ -f $PIDFILE ]; then
            		kill -HUP $PID
            		printf "%s\n" "Ok"
            		rm -f $PIDFILE
        	else
            		printf "%s\n" "pidfile not found"
        	fi
		;;
	restart)
    		$0 stop
    		$0 start
		;;
 
	*)
        	echo "Usage: $0 {status|start|stop|restart}"
esac

